// solid-frontend/src/components/StageCard.tsx
import { For, Show } from "solid-js";
import { Stage } from "../lib/api/v1";
import { Component } from "../lib/types";

import { Accordion } from "@kobalte/core/accordion";


export const StageCard: Component<{stage: Stage}> = (props) => {
    const stage = props.stage;



	return (
		<div
			use:melt={$item(stage.name ?? 'unnamed stage')}
			class="flex-1 my-3 rounded-lg pb-4 bg-bg-400"
		>
			<button
				use:melt={$trigger(stage.name ?? 'unnamed stage')}
				class="w-full text-3xl font-bold flex p-2 rounded-lg bg-bg-500 hover:scale-105 transition-all"
			>
				{stage.name ?? 'unnamed stage'}
				{#if (stage.bestOf ?? -1) > 0}
					<h2 class="flex-1 text-right">Best of {stage.bestOf ?? -1}</h2>
				{/if}
			</button>

<Show when={}>
			{#if $value === stage.name ?? 'unnamed stage'}
				<div
					use:melt={$content(stage.name ?? 'unnamed stage')}
					transition:slide={{ duration: 200 }}
				>
					<StageCard
						tournamentId={tournament.key?.id ?? -1}
						stage={{
							name: stage.name ?? 'unnamed stage',
							bestOf: stage.bestOf ?? -1,
							stageOrder: i
						}}
					/>
				</div>
			{/if}

</Show>
		</div>
	);
};

// frontend/src/components/StageCard.svelte
<script lang="ts">
	import type { PoolBracket } from '$lib/api/pool';
	import type { Stage } from '$lib/api/stages';
	import PoolList from './PoolList.svelte';

	export let stage: Stage;
	export let poolBrackets: PoolBracket[];
	export let hasBestOf: boolean;
</script>

<div class="rounded-lg pb-4 bg-bg-400 duration-200">
	<div class="flex p-2 rounded-lg bg-bg-500 hover:scale-105 transition-all">
		<h1 class="text-3xl font-bold">{stage.name}</h1>
		{#if hasBestOf} <h2 class="flex-1 text-right">Best of {stage.bestOf}</h2> {/if}
	</div>
	<div class="px-4 py-2">
		<PoolList brackets={poolBrackets} />
	</div>
</div>
